# Generated by Django 3.1.6 on 2021-03-30 11:39

import authapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20210315_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=authapp.models.default_expire_time),
        ),
    ]
